POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlaWtraSIsImlkIjoiNjY2MzFkOTg2N2E3ZTMxNjM3OGUwZmExIiwiaWF0IjoxNzE4MDI5MDU4fQ.7yHBnFetlHI6UQTDblpmu_X3rOEryc_l0e-95n0Iiyc

{
  "title": "Token test blog",
  "author": "token",
  "url": "http://www.token.com",
  "likes": 99
}